export type Cell = "YES" | "NO" | "PARTIAL" | "UNKNOWN" | "—";

export type PriorArtRow = {
  name: string;
  type: string;
  openSource: Cell;
  sdks: string;
  regressionTesting: Cell;
  equivalenceChecking: Cell;
  debuggingTracing: Cell;
  pytest: Cell;
  githubActions: Cell;
  cicd: Cell;
  crossVersion: Cell;
  crossSDK: Cell;
  bugCorpus: Cell;
  automatedFaultDetection: Cell;
  stateAwareAutonomous: Cell;
  overlap: string;
  sourceLabel: string;
  sourceUrl?: string;
};

export const PRIOR_ART: PriorArtRow[] = [
  {
    name: "MQT QCEC",
    type: "Library",
    openSource: "YES",
    sdks: "Qiskit, OpenQASM",
    regressionTesting: "NO",
    equivalenceChecking: "YES",
    debuggingTracing: "NO",
    pytest: "NO",
    githubActions: "PARTIAL",
    cicd: "PARTIAL",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "PARTIAL",
    stateAwareAutonomous: "NO",
    overlap: "Solves the equivalence-checking layer only",
    sourceLabel: "github.com/munich-quantum-toolkit/qcec",
    sourceUrl: "https://github.com/munich-quantum-toolkit/qcec",
  },
  {
    name: "MQT Debugger",
    type: "Library / tool",
    openSource: "YES",
    sdks: "OpenQASM",
    regressionTesting: "NO",
    equivalenceChecking: "NO",
    debuggingTracing: "YES",
    pytest: "NO",
    githubActions: "PARTIAL",
    cicd: "PARTIAL",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "PARTIAL",
    stateAwareAutonomous: "NO",
    overlap: "Solves single-run assertion debugging only",
    sourceLabel: "github.com/munich-quantum-toolkit/debugger",
    sourceUrl: "https://github.com/munich-quantum-toolkit/debugger",
  },
  {
    name: "QMon",
    type: "Monitoring tool",
    openSource: "UNKNOWN",
    sdks: "Unknown",
    regressionTesting: "NO",
    equivalenceChecking: "NO",
    debuggingTracing: "PARTIAL",
    pytest: "NO",
    githubActions: "UNKNOWN",
    cicd: "UNKNOWN",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "NO",
    stateAwareAutonomous: "NO",
    overlap: "Low — runtime monitoring only",
    sourceLabel: "arxiv.org/html/2512.13422",
    sourceUrl: "https://arxiv.org/html/2512.13422",
  },
  {
    name: "TraceQ",
    type: "Analysis tool",
    openSource: "UNKNOWN",
    sdks: "N/A (surface-code)",
    regressionTesting: "NO",
    equivalenceChecking: "NO",
    debuggingTracing: "YES",
    pytest: "NO",
    githubActions: "UNKNOWN",
    cicd: "UNKNOWN",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "NO",
    stateAwareAutonomous: "NO",
    overlap: "None — hardware / QEC focused",
    sourceLabel: "arxiv.org/pdf/2508.14533",
    sourceUrl: "https://arxiv.org/pdf/2508.14533",
  },
  {
    name: "Microsoft QDK Trace Simulator",
    type: "Product",
    openSource: "PARTIAL",
    sdks: "Q# / QDK",
    regressionTesting: "NO",
    equivalenceChecking: "NO",
    debuggingTracing: "YES",
    pytest: "NO",
    githubActions: "UNKNOWN",
    cicd: "UNKNOWN",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "NO",
    stateAwareAutonomous: "NO",
    overlap: "Low — resource estimation / debugging, single-run",
    sourceLabel: "Microsoft QDK documentation",
  },
  {
    name: "CUDA-Q Statistical Assertions",
    type: "Debugging technique",
    openSource: "UNKNOWN",
    sdks: "CUDA-Q",
    regressionTesting: "NO",
    equivalenceChecking: "NO",
    debuggingTracing: "YES",
    pytest: "NO",
    githubActions: "UNKNOWN",
    cicd: "UNKNOWN",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "PARTIAL",
    stateAwareAutonomous: "NO",
    overlap: "Low — single-run statistical debugging",
    sourceLabel: "arxiv.org/abs/2507.16255",
    sourceUrl: "https://arxiv.org/abs/2507.16255",
  },
  {
    name: "Proq",
    type: "Fault localization",
    openSource: "UNKNOWN",
    sdks: "Unknown",
    regressionTesting: "NO",
    equivalenceChecking: "NO",
    debuggingTracing: "YES",
    pytest: "NO",
    githubActions: "UNKNOWN",
    cicd: "UNKNOWN",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "YES",
    stateAwareAutonomous: "NO",
    overlap: "None — single-circuit fault localization",
    sourceLabel: "cited in arXiv:2506.18458",
    sourceUrl: "https://arxiv.org/abs/2506.18458",
  },
  {
    name: "Bloq / AutoBloq",
    type: "Fault localization",
    openSource: "UNKNOWN",
    sdks: "Unknown",
    regressionTesting: "NO",
    equivalenceChecking: "NO",
    debuggingTracing: "YES",
    pytest: "NO",
    githubActions: "UNKNOWN",
    cicd: "UNKNOWN",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "YES",
    stateAwareAutonomous: "NO",
    overlap: "None — single-circuit fault localization (outperforms Proq)",
    sourceLabel: "arXiv:2506.18458",
    sourceUrl: "https://arxiv.org/abs/2506.18458",
  },
  {
    name: "MorphQ",
    type: "Metamorphic testing",
    openSource: "YES",
    sdks: "Qiskit (tests the SDK itself)",
    regressionTesting: "PARTIAL",
    equivalenceChecking: "NO",
    debuggingTracing: "NO",
    pytest: "UNKNOWN",
    githubActions: "UNKNOWN",
    cicd: "UNKNOWN",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "YES",
    stateAwareAutonomous: "NO",
    overlap: "Partial — tests Qiskit itself, not user projects; not deeply verified",
    sourceLabel: "arXiv:2206.01111",
    sourceUrl: "https://arxiv.org/pdf/2206.01111",
  },
  {
    name: "Bugs4Q / Bugs4Q-Robust",
    type: "Bug corpus",
    openSource: "YES",
    sdks: "Qiskit",
    regressionTesting: "—",
    equivalenceChecking: "—",
    debuggingTracing: "—",
    pytest: "NO",
    githubActions: "NO",
    cicd: "—",
    crossVersion: "—",
    crossSDK: "—",
    bugCorpus: "YES",
    automatedFaultDetection: "NO",
    stateAwareAutonomous: "NO",
    overlap: "Reusable corpus, not a CI tool itself",
    sourceLabel: "github.com/Z-928/Bugs4Q",
    sourceUrl: "https://github.com/Z-928/Bugs4Q",
  },
  {
    name: "Cross-version Bugs4Q replication study",
    type: "Research study",
    openSource: "PARTIAL",
    sdks: "Qiskit (21 versions)",
    regressionTesting: "YES",
    equivalenceChecking: "NO",
    debuggingTracing: "NO",
    pytest: "NO",
    githubActions: "UNKNOWN",
    cicd: "UNKNOWN",
    crossVersion: "YES",
    crossSDK: "NO",
    bugCorpus: "PARTIAL",
    automatedFaultDetection: "YES",
    stateAwareAutonomous: "NO",
    overlap: "High — closest academic precedent for cross-version regression study",
    sourceLabel: "arXiv:2606.27124",
    sourceUrl: "https://arxiv.org/abs/2606.27124",
  },
  {
    name: "QBugs",
    type: "Bug corpus + infra",
    openSource: "YES",
    sdks: "Unknown (algorithmic)",
    regressionTesting: "—",
    equivalenceChecking: "—",
    debuggingTracing: "—",
    pytest: "UNKNOWN",
    githubActions: "UNKNOWN",
    cicd: "—",
    crossVersion: "—",
    crossSDK: "—",
    bugCorpus: "YES",
    automatedFaultDetection: "NO",
    stateAwareAutonomous: "NO",
    overlap: "Standardization attempt for debugging-technique comparison",
    sourceLabel: "arXiv:2103.16968",
    sourceUrl: "https://arxiv.org/abs/2103.16968",
  },
  {
    name: "QBugLM",
    type: "Agentic benchmark",
    openSource: "UNKNOWN",
    sdks: "OpenQASM 3 (framework-agnostic)",
    regressionTesting: "NO",
    equivalenceChecking: "NO",
    debuggingTracing: "NO",
    pytest: "NO",
    githubActions: "UNKNOWN",
    cicd: "UNKNOWN",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "YES",
    automatedFaultDetection: "YES",
    stateAwareAutonomous: "YES",
    overlap: "Closest agentic system found; no CI/CD, no cross-version",
    sourceLabel: "arXiv:2606.07314",
    sourceUrl: "https://arxiv.org/abs/2606.07314",
  },
  {
    name: "Qolumbina",
    type: "Benchmark suite",
    openSource: "YES",
    sdks: "Multiple (curated programs)",
    regressionTesting: "NO",
    equivalenceChecking: "NO",
    debuggingTracing: "NO",
    pytest: "UNKNOWN",
    githubActions: "UNKNOWN",
    cicd: "NO",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "PARTIAL",
    automatedFaultDetection: "NO",
    stateAwareAutonomous: "NO",
    overlap: "Benchmark corpus only, not a testing tool",
    sourceLabel: "arXiv:2607.02029",
    sourceUrl: "https://arxiv.org/abs/2607.02029",
  },
  {
    name: "QUTest",
    type: "Testing framework",
    openSource: "YES",
    sdks: "Qiskit only",
    regressionTesting: "YES",
    equivalenceChecking: "NO",
    debuggingTracing: "NO",
    pytest: "NO",
    githubActions: "YES",
    cicd: "YES",
    crossVersion: "YES",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "PARTIAL",
    stateAwareAutonomous: "NO",
    overlap: "HIGH — the most directly overlapping system found",
    sourceLabel: "arXiv:2605.19736",
    sourceUrl: "https://arxiv.org/abs/2605.19736",
  },
  {
    name: "Benchpress",
    type: "Benchmark suite",
    openSource: "YES",
    sdks: "Qiskit, Braket, Cirq, Tket, BQSKit, Staq, pyqpanda3, Qiskit IBM transpiler",
    regressionTesting: "NO",
    equivalenceChecking: "NO",
    debuggingTracing: "NO",
    pytest: "YES",
    githubActions: "NO",
    cicd: "NO",
    crossVersion: "NO",
    crossSDK: "YES",
    bugCorpus: "NO",
    automatedFaultDetection: "NO",
    stateAwareAutonomous: "NO",
    overlap:
      "Proves the pytest-native cross-SDK harness pattern at scale — but measures capability/performance only; detects no regressions or equivalence failures",
    sourceLabel: "github.com/Qiskit/benchpress",
    sourceUrl: "https://github.com/Qiskit/benchpress",
  },
  {
    name: "pytest-quantum",
    type: "pytest plugin",
    openSource: "YES",
    sdks: "Qiskit, Cirq, pytket",
    regressionTesting: "PARTIAL",
    equivalenceChecking: "PARTIAL",
    debuggingTracing: "NO",
    pytest: "YES",
    githubActions: "YES",
    cicd: "YES",
    crossVersion: "NO",
    crossSDK: "YES",
    bugCorpus: "NO",
    automatedFaultDetection: "PARTIAL",
    stateAwareAutonomous: "NO",
    overlap: "Partial — pytest-native + cross-framework equivalence, but no cross-version",
    sourceLabel: "github.com/qbench/pytest-quantum",
    sourceUrl: "https://github.com/qbench/pytest-quantum",
  },
  {
    name: "qtest-quantum",
    type: "pytest plugin",
    openSource: "YES",
    sdks: "Qiskit (implied)",
    regressionTesting: "PARTIAL",
    equivalenceChecking: "PARTIAL",
    debuggingTracing: "NO",
    pytest: "YES",
    githubActions: "YES",
    cicd: "YES",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "PARTIAL",
    stateAwareAutonomous: "NO",
    overlap: "Partial — pytest-native, single-SDK only, immature (0 stars)",
    sourceLabel: "github.com/metin-5115/qtest",
    sourceUrl: "https://github.com/metin-5115/qtest",
  },
  {
    name: "qc-assert",
    type: "pytest plugin",
    openSource: "YES",
    sdks: "Unknown",
    regressionTesting: "PARTIAL",
    equivalenceChecking: "NO",
    debuggingTracing: "NO",
    pytest: "YES",
    githubActions: "YES",
    cicd: "NO",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "NO",
    stateAwareAutonomous: "NO",
    overlap: "Minimal — intent stated, not implemented",
    sourceLabel: "github.com/JMORAF87/qc-assert",
    sourceUrl: "https://github.com/JMORAF87/qc-assert",
  },
  {
    name: "Qiskit ecosystem CI template",
    type: "CI template",
    openSource: "YES",
    sdks: "Qiskit",
    regressionTesting: "PARTIAL",
    equivalenceChecking: "NO",
    debuggingTracing: "NO",
    pytest: "UNKNOWN",
    githubActions: "YES",
    cicd: "YES",
    crossVersion: "YES",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "NO",
    stateAwareAutonomous: "NO",
    overlap: "Reusable version-tier CI, but no behavioral diffing or regression detection",
    sourceLabel: "github.com/Qiskit/qiskit-addon-cutting",
    sourceUrl: "https://github.com/Qiskit/qiskit-addon-cutting",
  },
  {
    name: "Qiskit QPY compat harness",
    type: "Internal CI",
    openSource: "YES",
    sdks: "Qiskit",
    regressionTesting: "YES",
    equivalenceChecking: "NO",
    debuggingTracing: "NO",
    pytest: "UNKNOWN",
    githubActions: "YES",
    cicd: "YES",
    crossVersion: "YES",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "YES",
    stateAwareAutonomous: "NO",
    overlap: "Narrow — serialization compatibility only, not externally reusable",
    sourceLabel: "github.com/Qiskit/qiskit (.github/workflows/qpy.yml)",
    sourceUrl: "https://github.com/Qiskit/qiskit/blob/main/.github/workflows/qpy.yml",
  },
  {
    name: "quantum-transpiler-regression-testing (“cart”)",
    type: "Research tool / pilot",
    openSource: "YES",
    sdks: "Qiskit transpiler only",
    regressionTesting: "YES",
    equivalenceChecking: "PARTIAL",
    debuggingTracing: "NO",
    pytest: "NO",
    githubActions: "UNKNOWN",
    cicd: "UNKNOWN",
    crossVersion: "NO",
    crossSDK: "NO",
    bugCorpus: "NO",
    automatedFaultDetection: "YES",
    stateAwareAutonomous: "NO",
    overlap: "High — closest regression-testing pilot; single-SDK, CLI, brand new, 0 stars",
    sourceLabel: "github.com/furqan-nr/quantum-transpiler-regression-testing",
    sourceUrl: "https://github.com/furqan-nr/quantum-transpiler-regression-testing",
  },
];
